name: 生成 GITHUB PROFILE 图片
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  generation:
    name: Compact display
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
     
      
